version: "3.8"

services:
  web_server:
    container_name: web_server
    image: nginx:alpine
    networks:
      - internal
    depends_on:
      - php_application
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./favicon.ico:/var/www/favicon.ico
    ports:
      - "8002:80"

  php_application:
    container_name: php_application
    build:
      context: ../..
      dockerfile: ./Docker/base/Dockerfile
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  internal: {}
